on:
  push:

name: Run mypy

jobs:
  build:
    name: Mypy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: actions/setup-python@v2

      - name: Install mypy
        run: pip install mypy

      - name: Run mypy
        run: mypy .
